name = "ContextualRobustOpt"
version = "0.1.0"
defaultTargets = ["ContextualRobustOpt"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"

[[lean_lib]]
name = "ContextualRobustOpt"
